### ISSUE TITLE
List view - dynamic is not a subtype of string

### ISSUE THREAD

**Issue by victorriveraiii** [joscmw95/geo_firestore#1]
My goal is to have a map that shows filtered markers from geo firestore, and the same filtered results in listview tiles below the map.  I've gotten the markers on the map working perfectly. 

populateClients() async {
Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
final queryLocation = GeoPoint(position.latitude, position.longitude);
List<DocumentSnapshot> documents = await geoFirestore.getAtLocation(queryLocation, 10.0);
documents.forEach((document) {
print(document.data);
});

The second part "listview" is what I'm having trouble with.  Here is what i've tried:

- streambuilder - populates listview with snapshot unfiltered data, does not work with .for each
- .tolist - does not contruct data in proper format for a list view
- create listview from clients or markers - only shows the first geoHash, many times (.length)
- only able to list geoHash, not title

Here is my submit code:

() async {
                      Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
            await geoFirestore.setLocation((roomnameController.text), GeoPoint(position.latitude, position.longitude));

- only two fields are passed, geoHash, and location(lat,lng)
   - it seems additional fields (from a form) cannot be passed using setLocation.

My next step is to try an inheritable widget but I feel like i'm going to have the same issues, but they will be available everywhere.

Am I approaching this wrong?  Did I use geofirestore correctly?  Any help is appreciated.

![goal1](https://user-images.githubusercontent.com/50765727/66259000-364b5600-e769-11e9-9649-75ad2f915a82.png)

**Comment by joscmw95** [comment]
Hi, GeoFirestore currently does not return data as a stream.
Right now it only supports querying a list of documents that is within the radius specified in a parameter.

`GeoFirestore.getAtLocation` returns `Future<List<DocumentSnapshot>>`
You can render the data in similar fashion as:

```dart
List<Map<String, dynamic>> _documents;

@override
void initState() {
  super.initState();
  populateClients();
}

populateClients() async {
  Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
  final queryLocation = GeoPoint(position.latitude, position.longitude);
  List<DocumentSnapshot> snapshots = await geoFirestore.getAtLocation(queryLocation, 10.0);
  final documents = snapshots.map((doc) {
    return doc.data;
  }).toList();
  setState(() {
    _documents = documents;
  });
}

@override
Widget build(BuildContext context) {
  return ListView(
    children: _documents.map((doc) {
      return Row(children: <Widget>[
          Text(doc['title']),
          Text(doc['description']),
        ]);
    }).toList(),
  );
}
```

**Comment by ggutenberg** [comment]
I've tried this code almost verbatim, but it's failing to retrieve any snapshots.  Using the node.js library works fine with the same center coordinates and same Firestore collection.  I'm new to Flutter/Dart so am not really sure how to debug this, so any help would be greatly appreciated.

Working (node.js):

```javascript
export const getNear = async (center: number[], radius: number) => {
  const geofirestore: GeoFirestore = new GeoFirestore(firestore);
  const geocollection: GeoCollectionReference = geofirestore.collection(
    "businesses"
  );
  const query: GeoQuery = geocollection.near({
    center: new admin.firestore.GeoPoint(center[0], center[1]),
    radius
  });
  const queryResults = await query.get();
  console.log(queryResults.docs);
  return queryResults.docs.map(doc => doc.data());
};

const getNearResponse = await business.getNear(
  [-1.7970149, -80.757148],
  1000
);
```

Not working (Dart):

```dart
  _populateBusinesses() async {
    final GeoFirestore geocollection =
        GeoFirestore(firestore.collection('businesses'));
    final queryLocation = GeoPoint(-1.7970149, -80.757148);
    List<DocumentSnapshot> snapshots =
        await geocollection.getAtLocation(queryLocation, 1000);
    // snapshots is always an empty List
    final documents = snapshots.map((doc) {
      return doc.data;
    }).toList();
    setState(() {
      _documents = documents;
    });
  }
```

**Comment by victorriveraiii** [comment]
This answer was so helpful.  Is it possible to create a new document in firestore from the query?  This way I can use the firestore function oncreate() to send message to the results of this query?

**Comment by joscmw95** [comment]
Hi, you can add or update documents as you normally would with Firestore and set a geohash location using the helper method `geoFirestore.setLocation);`. To keep the issue list free of adhoc questions and since this is out of what the issue was opened for, I'm closing this issue.

Note that I'm not actively maintaining this package, there is another more popular GeoFlutterFirestore package, check out [GeoFlutterFire](https://github.com/DarshanGowda0/GeoFlutterFire).

Feel free to email me if you have any more questions.

**Comment by victorriveraiii** [comment]
oh, bummer.  This was working great so far.  i was trying:

```dart
populateClientu() async {
  Position position = await Geolocator()
      .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
  var queryLocation = GeoPoint(position.latitude, position.longitude);
  List<DocumentSnapshot> snapshots =
      await geoFirestore.getAtLocation(queryLocation, 100.0);
  final documents = snapshots.map((doc) {
    return doc.data;
  }).toList();

  setState(() {
    _documents = documents;
  });

  db.collection('messages').document().setData({
    'token': documents,
  });
}
```

I'm not sure if it working properly, any advise is appreciated.  I looked at GeoFlutterFire and it's not able to do the same things that I use geo_firestore for.
